export interface Item {
    id?: string,
    company?: string,
    model?: string,
    lens?: string,
    megapixel?: string,
    sensor?: string,
    iso?: string,
    shutterspeed?: string,
    focuspoint?: string,
    coverage?: string,
    fps?: string,
    afvideo?: string,
    flash?: string,
    media?: string,
    dimension?: string,
    processor?: string,
    lcd?: string,
    weight?: string,
    life?: string,
    image?: string,
  }